version: "3"

services:
  # Defines a service named "workspace"
  workspace:
    build:
      # Sets the build context to the current directory
      context: .
      # Specifies the Dockerfile to use for the build
      dockerfile: .docker/Dockerfile.app
      # Specifies build-time variables (ARGs)
      args:
        ARG_BUILD_FROM: $BUILD_FROM
        ARG_USERNAME: $USERNAME
        ARG_USER_UID: $USER_UID
        ARG_USER_GID: $USER_GID
        ARG_WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
        ARG_USER_FULLNAME: $APP_USER_FULLNAME
        ARG_USER_EMAIL: $APP_USER_EMAIL
        ARG_GITHUB_USERNAME: $GITHUB_USERNAME
        ARG_SYSTEM_HOSTNAME: $CONTAINER_HOSTNAME
        ARG_WORKSPACE_LOCATION: $CONTAINER_WORKSPACE_LOCATION
        ARG_DOTFILES_VERSION: $DOTFILES_VERSION
        ARG_APP_GITHUB_USERNAME: $APP_GITHUB_USERNAME
        ARG_APP_SOURCE_REPO: $APP_SOURCE_REPO
        ARG_APP_INSTALL_ROOT: $APP_INSTALL_ROOT
        ARG_APP_CLONE_DIRNAME: $APP_CLONE_DIRNAME
        ARG_APP_SOURCE_BRANCH: $APP_SOURCE_BRANCH
        ARG_APP_SERVER_NAME: $APP_SERVER_NAME
    # Sets the image name for the built image
    image: $IMAGE_NAME:$IMAGE_TAG
    # Sets the hostname of the container
    hostname: $CONTAINER_HOSTNAME
    command:
      # Specifies the command to be executed when the container is run
      - bash
      - $LAUNCH_SCRIPT
    # set the environment variables
    environment:
      USER_FULLNAME: $APP_USER_FULLNAME
      USER_EMAIL: $APP_USER_EMAIL
      GITHUB_USERNAME: $APP_GITHUB_USERNAME
      WORKSPACE_LOCATION: $CONTAINER_WORKSPACE_LOCATION
      WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
      SYSTEM_HOSTNAME: $CONTAINER_HOSTNAME
      HOST_JUPYTER_PORT: $HOST_JUPYTER_PORT
      JUPYTER_PORT: $JUPYTER_PORT
      JUPYTER_TOKEN: $JUPYTER_TOKEN
      VARIANT: $VARIANT
      GIT_COMMIT_GPGSIGN: $GIT_COMMIT_GPGSIGN
    ulimits:
      # Sets the stack size and memory lock limits
      stack: 67108864
      memlock: -1
    # Allows the container to use the host's IPC namespace
    ipc: $CONTAINER_IPC
    ports:
      # Maps the container's SSH and Web service ports to the host's ports
      - "$HOST_SSH_PORT:$SSH_PORT"
      - "$HOST_JUPYTER_PORT:$JUPYTER_PORT"
      - "$HOST_WEB_SVC_PORT:$WEB_SVC_PORT"
    volumes:
      # Maps directories from the host to the container
      - "$HOME/.cache:/home/$USERNAME/.cache"
      - "$PWD/.docker/scripts:$CONTAINER_WORKSPACE_ROOT/scripts"
      - "$HOME/.ssh:/home/$USERNAME/.ssh"
      - "$PWD/workspace:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/workspace"
      - "$PWD/workspace/config_states:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/config_states"
      - "$PWD/workspace/embeddings:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/embeddings"
      - "$PWD/workspace/extensions:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/extensions"
      - "$PWD/workspace/interrogate:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/interrogate"
      - "$PWD/workspace/localizations:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/localizations"
      - "$PWD/workspace/log:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/log"
      - "$PWD/workspace/models:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/models"
      - "$PWD/workspace/outputs:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/outputs"
      # - "$PWD/workspace/repositories:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/repositories"
      - "$PWD/workspace/textual_inversion:$APP_INSTALL_ROOT/$APP_CLONE_DIRNAME/textual_inversion"
    deploy:
      resources:
        reservations:
          devices:
            # Reserves the specified GPU for the container
            - driver: nvidia
              device_ids: ["${CUDA_DEVICE_ID}"]
              capabilities: [gpu]
networks:
  default:
    # Sets the name of the default network and makes it external
    name: $DOCKER_NETWORK_NAME
    external: true
